<a href="https://colab.research.google.com/github/swethanuchu/ACE-BOOTCAMP-2026/blob/main/Numpybootcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)
arr1=np.array([[[1,2,3,4],[5,6,7,8],[5,6,7,8]],
              [[1,2,3,4],[5,6,7,8],[5,6,7,8]],
              [[1,2,3,4],[5,6,7,8],[5,6,7,8]]])
print(arr1)
#to check dimensions of an Array in Numpy
print(arr1.ndim)
print(arr1.shape)
print(arr1[2,0,1])
print(arr1[2][1][3])

2.0.2
[[[1 2 3 4]
  [5 6 7 8]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]
  [5 6 7 8]]]
3
(3, 3, 4)
2
8


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],
              [1,2,3,4]])
print(arr[1:2,1])

[2]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],
              [1,12,3,4]])
print(arr[:,1:3])


[[ 2  3]
 [12  3]]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],
              [1,12,3,4]])
print(arr[:,2:4])


[[3 4]
 [3 4]]


In [ ]:
####Arithmetic(Operators and functions)
#Scalar Arithmetics(operations perform using a single value)
import numpy as np
arr=np.array([1,4,5,8,9])
my_list=[1,4,5,8,9]
print("adding elements:",arr*2)


adding elements: [ 2  8 10 16 18]


In [ ]:
####Arithmetic(Operators and functions)
#Scalar Arithmetics(operations perform using a single value)
import numpy as np
arr=np.array([1,4,5,8,9])
my_list=[1,4,5,8,9]
print("Addition of elements with 5:",arr+5)


Addition of elements with 5: [ 6  9 10 13 14]


In [ ]:
####Arithmetic(Operators and functions)
#Scalar Arithmetics(operations perform using a single value)
import numpy as np
arr=np.array([1,4,5,8,9])
my_list=[1,4,5,8,9]
print("Subtraction of elements:",arr-2)
print("Division of elements:",arr%4)

Subtraction of elements: [-1  2  3  6  7]
Division of elements: [1 0 1 0 1]


In [ ]:
import numpy as np
arr1=np.array([1,4,5,8,9])
arr2=np.array([1,4,5,8,9])
print(arr1*2)
print(np.add(2,arr1))
print(np.divide(2,arr1))
print(np.multiply(2,arr1))
print(np.subtract(2,arr1))
print(np.sum(arr1))



[ 2  8 10 16 18]
[ 3  6  7 10 11]
[2.         0.5        0.4        0.25       0.22222222]
[ 2  8 10 16 18]
[ 1 -2 -3 -6 -7]
27


In [ ]:
import numpy as np
arr=np.array([1,4,5,8,9],[1,14,5,8,9],[1,14,5,18,9])
print("actual array:",arr)
print("sum of the elements Using Vector:",np.sum(arr,0))



actual array: [[ 1  4  5  8  9]
 [ 1 14  5  8  9]
 [ 1 14  5 18  9]]
sum of the elements Using Vector: [ 3 32 15 34 27]


In [ ]:
import numpy as np
arr=np.array[[1,2,3,4]]
arr1=np.array[[5,6,7,8]]
print("addition is:",arr+arr1)
print("multiplication is:\n",arr@arr1)
print("multiplication is:",np.matmul(arr,arr1))

TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
marks=np.array([[95,100,1,55,68],
                [25,45,63,77,68]])
marks[marks<50]=0
print(marks)
marks[(marks>50)&(marks<70)]=0
print(marks)
print("comparision:")
print(np.mean(arr))
print(np.var(arr))
print(np.std(arr))
print(np.sqrt(np.std(arr)))
print(np.var(arr))
print(np.max(arr))
print(np.min(arr))
print(np.argmin(arr))
print(np.argmax(arr))

[[ 95 100   0  55  68]
 [  0   0  63  77  68]]
[[ 95 100   0   0   0]
 [  0   0   0  77   0]]
comparision:
2.5
1.25
1.118033988749895
1.057371263440564
1.25
4
1
0
3


In [ ]:
import numpy as np
arr=np.array([[1,2]])
arr1=np.array([[1],[2],[3],[4]])
print("Shape of array:",arr.shape)
print("Shape of array:",arr1.shape)
print(arr*arr1)

Shape of array: (1, 2)
Shape of array: (4, 1)
[[1 2]
 [2 4]
 [3 6]
 [4 8]]


In [ ]:
import numpy as np
arr=np.array([[1,2],[8,8],[3,3],[5,5]])
arr1=np.array([[1,6],[1,2],[3,3],[6,6]])
print("multiplication is:\n",arr*arr1)
print("Shape of array:",arr.shape)
print("Shape of array:",arr1.shape)
print(arr*arr1)

multiplication is:
 [[ 1 12]
 [ 8 16]
 [ 9  9]
 [30 30]]
Shape of array: (4, 2)
Shape of array: (4, 2)
[[ 1 12]
 [ 8 16]
 [ 9  9]
 [30 30]]


In [ ]:
%%writefile shuffle_demo.py
import numpy as np
ran=np.random.default_rng()
print(ran.integers(6))
print(ran.uniform(low=10,high=90,size=10))
laptops=np.array(["HP","Lenovo","Dell","MacAir","Toshiba"])
ran.shuffle(laptops,axis=0)
print(laptops)
print(ran.choice(laptops))

Writing shuffle_demo.py
